load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_binary(
    name = "main",
    srcs = [
        "main.cpp",
    ],
    deps = [
        ":lib",
    ],
)

cc_library(
    name = "lib",
    srcs = [
        "arg_parser.cpp",
        "game_library.cpp",
        "platform.cpp",
    ],
    hdrs = [
        "arg_parser.h",
        "game_library.h",
        "platform.h",
    ],
    deps = [
        "//dali/core",
        "//third_party:glad",
        "//third_party:nfd",
        "//third_party:sdl3",
        "//third_party:imgui_sdl3_opengl3",
    ],
)

cc_test(
    name = "test",
    srcs = [
        "arg_parser_test.cpp",
    ],
    deps = [
        ":lib",
        "//third_party:catch2",
    ],
)
