# load("//kandinsky:cc_rules.bzl", "kdk_cc_library", "kdk_cc_test")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "core",
    srcs = [
        "defines.cpp",
        "filesystem.cpp",
        "math.cpp",
        "memory.cpp",
        "string.cpp",
    ],
    hdrs = [
        "algorithm.h",
        "array.h",
        "container.h",
        "defines.h",
        "filesystem.h",
        "function.h",
        "math.h",
        "memory.h",
        "string.h",
    ],
    linkopts = ["-DEFAULTLIB:Dbghelp.lib"],
    deps = [
        "//third_party:cwalk",
        "//third_party:sdl3",
        "//third_party:stb",
        "//third_party:glm",
    ],
)

cc_test(
    name = "tests",
    srcs = [
        "function_test.cpp",
    ],
    testonly = True,
    size = "small",
    # data = [
    #     "//testing/testdata:file_testdata",
    # ],
    defines = ["KDK_IN_TEST=1"],
    deps = [
        ":core",
        "//third_party:catch2",
    ],
)

cc_test(
    name = "function_allocation_test",
    srcs = [
        "function_allocation_test.cpp",
    ],
    testonly = True,
    size = "small",
    # data = [
    #     "//testing/testdata:file_testdata",
    # ],
    defines = ["KDK_IN_TEST=1"],
    deps = [
        ":core",
        # "//third_party:catch2",
    ],
)
